repos:
  - repo: https://github.com/ipfans/pre-commit-hooks
    rev: v0.3.0
    hooks:
      - id: go-fumpt
      - id: go-imports
      - id: go-vet
      - id: go-cyclo
        args: [-over=15]
      - id: golangci-lint
      - id: go-critic
      - id: go-unit-tests
      - id: go-build
      - id: go-generate
      - id: go-mod-tidy
      - id: commit-msg-checker
